---
# tasks file for Tom
  - name: Update all packages to the latest version
    apt:
      upgrade: dist 
  - name: Installing Java 11
    apt:
      name: openjdk-11-jdk
      state: present
  - name: Downloading tomcat
    get_url:
      url: https://apachemirror.wuchna.com/tomcat/tomcat-10/v10.0.6/bin/apache-tomcat-10.0.6.tar.gz
      dest: /opt
      mode: '777'
  - name: Unarchiving Tomcat
    unarchive:
      src: /opt/apache-tomcat-10.0.6.tar.gz
      dest: /opt
      remote_src: yes 
      mode: '777'
  - name: Changing port number
    template:
      src: /home/ubuntu/server.xml.j2
      dest: /opt/apache-tomcat-10.0.6/conf/server.xml
      mode: '777'
  - name: Stoping Tomcat
    shell: nohup /opt/apache-tomcat-10.0.6/bin/shutdown.sh &
  - name: Starting Tomcat
    shell: nohup /opt/apache-tomcat-10.0.6/bin/startup.sh &
  - name: Downloading sample war file
    get_url:
      url: https://tomcat.apache.org/tomcat-7.0-doc/appdev/sample/sample.war
      dest: /opt/apache-tomcat-10.0.6/webapps
      mode: '777'
